import React, { createContext, useContext, useState } from "react";

// Create a context
const QrDataContext = createContext();

// Create a provider component
export const QrDataProvider = ({ children }) => {
  const initialState = {
    qr_name: "",
    id: "",
    field_url: "",
    network_name: "",
    network_password: "",
    network_security_type: "",
    youtube_url: "",
    pdf_file: "",
    pdf_company: "",
    pdf_title: "",
    pdf_description: "",
    pdf_website: "",
    app_name: "",
    app_company: "",
    app_description: "",
    app_logo: "",
    app_website: "",
    app_social: {},
    landing_action_url: "",
    landing_company: "",
    landing_logo: "",
    landing_title: "",
    landing_subtitle: "",
    landing_social: {},
    landing_btn_text: "",
    media_social: {},
    media_headline: "",
    media_description: "",
    gallery_image: "",
    gallery_title: "",
    gallery_description: "",
    gallery_website: "",
    gallery_url: "",
    gallery_btn_text: "",
    links_image: "",
    links_title: "",
    links_description: "",
    all_links: [],
    links_social: {},
    vcard_address: "",
    vcard_city: "",
    vcard_company_name: "",
    vcard_country: "",
    vcard_email: "",
    vcard_fax: "",
    vcard_full_name: "",
    vcard_landline_phone: "",
    vcard_mobile_phone: "",
    vcard_numeration: "",
    vcard_profession: "",
    vcard_state: "",
    vcard_summary: "",
    vcard_website: "",
    vcard_zip_code: "",
    vcard_social: "",
    vcard_image: "",
    business_email: "",
    business_name: "",
    business_phone: "",
    business_website: "",
    business_action_title: "",
    business_url: "",
    business_company: "",
    business_subtitle: "",
    business_title: "",
    business_btn_text: "",
    business_address: "",
    business_city: "",
    business_country: "",
    business_numeration: "",
    business_postalcode: "",
    business_state: "",
    business_about: "",
    opening_hours_days: {
      monday: { enabled: false, times: [] },
      tuesday: { enabled: false, times: [] },
      wednesday: { enabled: false, times: [] },
      thursday: { enabled: false, times: [] },
      friday: { enabled: false, times: [] },
      saturday: { enabled: false, times: [] },
      sunday: { enabled: false, times: [] },
    },
    opening_hours_format: "AM-PM",
    business_facilities: "",
    business_social: "",
    business_logo: "",
    video: null,
    video_name: "",
    video_description: "",
    video_button: "",
    video_url: "",
    video_social: {},
    event_action_title: "",
    event_action_url: "",
    event_description: "",
    event_title: "",
    event_location_address: "",
    event_location_city: "",
    event_location_country: "",
    event_location_numeration: "",
    event_location_postal_code: "",
    event_location_state: "",
    event_organizer_about: "",
    event_organizer_email: "",
    event_organizer_name: "",
    event_organizer_phone: "",
    event_organizer_website: "",
    event_time_action_title: "",
    event_time_all_day: true,
    event_time_end: "2024-09-29T19:00:00.000Z",
    event_time_start: "2024-09-28T19:00:00.000Z",
    event_time_timezone: "",
    event_image: "",
    event_facilities: "",
    event_btn_text: "",
    type: "",
    style: {
      dotsStyle: "", // square
      dotsColor: "#000000",
      cornerStyle: "",
      cornerBackgroundColor: "#ffffff",
      cornerBorderColor: "",
      cornerDotColor: "",
      backgroundColor: "",
      frameStyle: "",
      frameColor: "#404040",
      frameText: "",
      frameTextColor: "",
      frameName: "",
    },
    color: {
      background: "",
      button: "",
    },
    social: {},
  };

  const [qrData, setQrData] = useState(initialState);

  return (
    <QrDataContext.Provider value={{ qrData, setQrData }}>
      {children}
    </QrDataContext.Provider>
  );
};

// Custom hook to use the QrDataContext
export const useQrData = () => {
  return useContext(QrDataContext);
};
